### ISSUE TITLE
Point values discrepancy/Stuff I noticed

### ISSUE THREAD

**Issue by RenMomo96** [BSData/zone-raiders#14]
just gonna make a list of stuff that's wrong or missing points value wise that I have noticed thus far

Zone Stalkers: 

Interdiction Rifle and Vesper Rifle have mixed up point values, should be vesper has 30 and interdiction has 50

Explosive trap should be 20 points, Self replenishing smoke should be 15, and Rangefinder scope should be 25

Reclaimers:

Alloy Magnum should be in faction secondary weapons

Nthgens:

Faction armors have no values, same for faction weapons

those are the only things I have noticed, the rest of it has been really helpful so far and thank you for making the list builder, has really helped a lot :)

**Comment by DanieleSuppo** [comment]
Thanks for the feedback!
I will be able to implement the changes starting from the next week, a little holiday here ;)

Thanks
Daniele

**Comment by DanieleSuppo** [comment]
All theissues mentioned should be fixed with release v1.1
