### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by gannj001** [BSData/zone-raiders#18]
I'd like to add the factions from Conflict Modus if possible? Starting with the Moto-runners

**Comment by DanieleSuppo** [comment]
Sure, you can create a branch on the repo you forked (or work directly on the master) and then do the Pull Request, so I can merge in the live repository.

Thanks for helping!

**Comment by DanieleSuppo** [comment]
Hello @gannj001 any news on it?
Did you start working on Conflict Modus factions?
Realy looking forward to see it if you started.

Regards
Daniele

**Comment by gannj001** [comment]
I have done some work! Still not ready for any eyes but mine, trying to get my head around how to do the BioKriegers...
